# Generated by Django 3.0.8 on 2020-07-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=120)),
                ('ipadress', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=120)),
            ],
        ),
    ]
