# Generated by Django 3.0.8 on 2020-07-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_server_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='timestamp',
        ),
    ]
